const Achievements = {
  data: { firstPractice:false,xp10:false,xp100:false,questions100:false,streak3:false,streak7:false,streak30:false,accuracy10:false,accuracy50:false,accuracy100:false,accuracy200:false,chapterAchievements:{} },
  definitions: {
    firstPractice:{title:'First Practice',description:'Complete your first practice question',target:1,type:'questions'}, xp10:{title:'10 XP Master',description:'Earn your first 10 XP',target:10,type:'xp'}, xp100:{title:'100 XP Learner',description:'Reach 100 XP',target:100,type:'xp'}, questions100:{title:'100 Questions',description:'Complete 100 practice questions',target:100,type:'questions'},
    streak3:{title:'First Streak',description:'Study for 3 consecutive days',target:3,type:'streak'}, streak7:{title:'Weekly Warrior',description:'Study for 7 consecutive days',target:7,type:'streak'}, streak30:{title:'Monthly Master',description:'Study for 30 consecutive days',target:30,type:'streak'}, accuracy10:{title:'Sharp Learner',description:'10 correct answers in a row',target:10,type:'correctStreak'}, accuracy50:{title:'Precision Student',description:'50 correct answers in a row',target:50,type:'correctStreak'}, accuracy100:{title:'IB Accuracy Master',description:'100 correct answers in a row',target:100,type:'correctStreak'}, accuracy200:{title:'Perfect Streak',description:'200 correct answers in a row',target:200,type:'correctStreak'}
  },
  chapterDefinitions: {
    starter:{title:'Chapter Starter',targetQuestions:10,targetAccuracy:0,description:'Answer 10 questions in a chapter'}, learner:{title:'Chapter Learner',targetQuestions:30,targetAccuracy:70,description:'Answer 30 questions with at least 70% accuracy'}, master:{title:'Chapter Master',targetQuestions:50,targetAccuracy:85,description:'Answer 50 questions with at least 85% accuracy'}, expert:{title:'Chapter Expert',targetQuestions:100,targetAccuracy:90,description:'Answer 100 questions with at least 90% accuracy'}
  },
  selectedTrophySubject:null,newlyUnlocked:[],notificationTimer:null,
  load(){ const saved=Storage.load('ib_achievements'); if(saved)this.data={...this.data,...saved,chapterAchievements:saved.chapterAchievements||{}}; this.render(); },
  check(progress){
    const before={...this.data,chapterAchievements:JSON.parse(JSON.stringify(this.data.chapterAchievements||{}))};
    this.data.firstPractice ||= progress.questions>0; this.data.xp10 ||= progress.xp>=10; this.data.xp100 ||= progress.xp>=100; this.data.questions100 ||= progress.questions>=100;
    const streak=typeof Streak!=='undefined'?Streak.data.count:0; this.data.streak3 ||= streak>=3; this.data.streak7 ||= streak>=7; this.data.streak30 ||= streak>=30;
    const correctStreak=progress.correctStreak||0; this.data.accuracy10 ||= correctStreak>=10; this.data.accuracy50 ||= correctStreak>=50; this.data.accuracy100 ||= correctStreak>=100; this.data.accuracy200 ||= correctStreak>=200;
    this.checkChapterAchievements(progress);
    const newlyUnlockedGlobal=Object.keys(this.definitions).filter(k=>this.data[k]&&!before[k]).map(k=>({type:'global',key:k,title:this.definitions[k].title}));
    const newlyUnlockedChapter=[]; Object.entries(this.data.chapterAchievements||{}).forEach(([subject,chapters])=>Object.entries(chapters||{}).forEach(([chapter,achievements])=>Object.keys(this.chapterDefinitions).forEach(k=>{if(achievements[k]&&!before.chapterAchievements?.[subject]?.[chapter]?.[k])newlyUnlockedChapter.push({type:'chapter',key:k,title:this.chapterDefinitions[k].title,subject,chapter});})));
    this.newlyUnlocked=[...newlyUnlockedGlobal,...newlyUnlockedChapter]; Storage.save('ib_achievements',this.data); this.render(); this.showNotification();
  },
  checkChapterAchievements(progress){
    const chapterStats=progress?.chapterStats||{}; Object.entries(chapterStats).forEach(([subject,chapters])=>{if(!this.data.chapterAchievements[subject])this.data.chapterAchievements[subject]={}; Object.entries(chapters).forEach(([chapter,stats])=>{if(!this.data.chapterAchievements[subject][chapter])this.data.chapterAchievements[subject][chapter]={}; const questions=stats.questions||0,accuracy=questions>0?(stats.correct/questions)*100:0,earned=this.data.chapterAchievements[subject][chapter]; Object.entries(this.chapterDefinitions).forEach(([key,def])=>{if(!earned[key]&&questions>=def.targetQuestions&&accuracy>=def.targetAccuracy)earned[key]=true;});});});
  },
  getChapterProgress(subject,chapter,progress=Progress.data){const stats=progress?.chapterStats?.[subject]?.[chapter]||{questions:0,correct:0}; const accuracy=stats.questions>0?Math.round(stats.correct/stats.questions*100):0; const achievements=this.data.chapterAchievements?.[subject]?.[chapter]||{}; return {...stats,accuracy,achievements};},
  getProgress(item,progress){const current={questions:progress?.questions||0,xp:progress?.xp||0,streak:typeof Streak!=='undefined'?Streak.data.count||0:0,correctStreak:progress?.correctStreak||0};return Math.min(current[item.type]||0,item.target);},
  getTrophyRank(unlocked,total){const p=total>0?unlocked/total*100:0;if(p>=80)return{title:'Master',icon:'👑',description:'Exceptional achievement collection.'};if(p>=60)return{title:'Expert',icon:'🏆',description:'A highly accomplished IB learner.'};if(p>=40)return{title:'Advanced',icon:'🎓',description:'Your achievement collection is growing strongly.'};if(p>=20)return{title:'Learner',icon:'📘',description:'Keep practicing to build your collection.'};return{title:'Rookie',icon:'🌱',description:'Start practicing to build your collection.'};},
  getTrophySubjects(progress){return Object.keys(progress?.chapterStats||{});},
  selectTrophySubject(subject){this.selectedTrophySubject=subject;this.renderTrophyRoom(typeof Progress!=='undefined'?Progress.data:{});},
  bindTrophyTabs(){const area=document.getElementById('trophy-subject-tabs');if(!area)return;area.querySelectorAll('.trophy-subject-tab').forEach(button=>{button.addEventListener('click',()=>{const subject=button.dataset.subject;if(subject)this.selectTrophySubject(subject);});});},
  renderTrophyRoom(progress){
    const globalEntries=Object.entries(this.definitions),subjects=this.getTrophySubjects(progress); let chapterTotal=0,chapterUnlocked=0;
    Object.values(progress.chapterStats||{}).forEach(chapters=>Object.keys(chapters||{}).forEach(()=>chapterTotal+=Object.keys(this.chapterDefinitions).length));
    Object.values(this.data.chapterAchievements||{}).forEach(chapters=>Object.values(chapters||{}).forEach(a=>Object.keys(this.chapterDefinitions).forEach(k=>{if(a?.[k])chapterUnlocked++;})));
    const globalUnlocked=globalEntries.filter(([k])=>Boolean(this.data[k])).length,total=globalEntries.length+chapterTotal,unlocked=globalUnlocked+chapterUnlocked,percent=total>0?Math.round(unlocked/total*100):0,rank=this.getTrophyRank(unlocked,total);
    if(!this.selectedTrophySubject||!subjects.includes(this.selectedTrophySubject))this.selectedTrophySubject=subjects[0]||null;
    const set=(id,value)=>{const el=document.getElementById(id);if(el)el.textContent=value;}; const bar=document.getElementById('trophy-summary-bar');
    set('trophy-unlocked-count',`${unlocked} / ${total}`);if(bar)bar.style.width=`${percent}%`;set('trophy-summary-percent',`${percent}% Complete`);set('trophy-rank-icon',rank.icon);set('trophy-rank-title',rank.title);set('trophy-rank-description',rank.description);
    const tabsArea=document.getElementById('trophy-subject-tabs');
    if(tabsArea){tabsArea.innerHTML=subjects.length?subjects.map(subject=>`<button type="button" class="trophy-subject-tab ${subject===this.selectedTrophySubject?'active':''}" role="tab" aria-selected="${subject===this.selectedTrophySubject}" data-subject="${String(subject).replace(/"/g,'&quot;')}">${subject}</button>`).join(''):'<span class="muted">No chapter data yet.</span>';this.bindTrophyTabs();}
    const chapterArea=document.getElementById('trophy-chapter-list');if(!chapterArea)return;if(!this.selectedTrophySubject){chapterArea.innerHTML='<p class="muted">Complete practice questions to unlock chapter trophies.</p>';return;}
    const chapters=progress.chapterStats?.[this.selectedTrophySubject]||{};
    chapterArea.innerHTML=Object.entries(chapters).map(([chapter])=>{const current=this.getChapterProgress(this.selectedTrophySubject,chapter,progress);const cards=Object.entries(this.chapterDefinitions).map(([key,def])=>{const done=Boolean(current.achievements[key]);const pp=def.targetAccuracy>0?Math.min(100,Math.round(Math.min(current.questions/def.targetQuestions,1)*50+Math.min(current.accuracy/def.targetAccuracy,1)*50)):Math.min(100,Math.round(current.questions/def.targetQuestions*100));return `<div class="chapter-achievement ${done?'unlocked':'locked'}"><strong>${done?'🏆':'🔒'} ${def.title}</strong><span>${current.questions}/${def.targetQuestions} · ${current.accuracy}%</span><small>${def.description}</small><div class="achievement-progress-track"><span style="width:${pp}%"></span></div></div>`;}).join('');return `<article class="chapter-progress-card"><h4>${this.selectedTrophySubject} — ${chapter}</h4><p><strong>${current.accuracy}%</strong> · ${current.correct}/${current.questions} correct</p>${cards}</article>`;}).join('')||'<p class="muted">No chapter progress for this subject yet.</p>';
  },
  showNotification(){if(!this.newlyUnlocked.length)return;const globalNames=this.newlyUnlocked.filter(i=>i.type==='global').map(i=>i.title),chapterItems=this.newlyUnlocked.filter(i=>i.type==='chapter'),lines=[];if(globalNames.length)lines.push(globalNames.join(' · '));chapterItems.forEach(i=>lines.push(`${i.title} — ${i.subject} / ${i.chapter}`));let toast=document.getElementById('achievement-toast');if(!toast){toast=document.createElement('div');toast.id='achievement-toast';toast.setAttribute('role','status');toast.setAttribute('aria-live','polite');document.body.appendChild(toast);}toast.innerHTML=`🏆 Achievement Unlocked!<br><span>${lines.join('<br>')}</span>`;toast.style.display='block';if(this.notificationTimer)clearTimeout(this.notificationTimer);this.notificationTimer=setTimeout(()=>{toast.style.display='none';this.notificationTimer=null;},3000);this.newlyUnlocked=[];},
  render(){
    const progress=typeof Progress!=='undefined'?Progress.data:{};const fullArea=document.getElementById('achievement-list'),practiceArea=document.getElementById('practice-achievement-list');
    if(fullArea)fullArea.innerHTML=Object.entries(this.definitions).map(([key,item])=>{const unlocked=Boolean(this.data[key]);return `<article class="achievement-card ${unlocked?'unlocked':'locked'}"><h3>${unlocked?'🏆':'🔒'} ${item.title}</h3><p>${item.description}</p><small>${unlocked?'Unlocked':'Locked'}</small></article>`;}).join('');
    if(practiceArea)practiceArea.innerHTML=Object.entries(this.definitions).map(([key,item])=>{const unlocked=Boolean(this.data[key]),current=this.getProgress(item,progress),pct=Math.round(current/item.target*100);return `<article class="achievement-card achievement-progress-card ${unlocked?'unlocked':'locked'}"><div class="achievement-progress-header"><h3>${item.title}</h3><strong>${current}/${item.target}</strong></div><div class="achievement-progress-track" role="progressbar" aria-valuemin="0" aria-valuemax="${item.target}" aria-valuenow="${current}"><span style="width:${pct}%"></span></div><small>${unlocked?'Completed':item.description}</small></article>`;}).join('');
    const chapterProgressArea=document.getElementById('chapter-progress-list');if(chapterProgressArea)chapterProgressArea.innerHTML=Object.entries(progress.chapterStats||{}).map(([subject,chapters])=>`<section class="chapter-progress-subject"><h3>${subject}</h3>${Object.entries(chapters).map(([chapter])=>{const current=this.getChapterProgress(subject,chapter,progress);return `<article class="chapter-progress-card"><h4>${subject} — ${chapter}</h4><p><strong>${current.accuracy}%</strong> · ${current.correct}/${current.questions} correct</p>${Object.entries(this.chapterDefinitions).map(([key,def])=>`<div class="chapter-achievement ${current.achievements[key]?'unlocked':'locked'}"><strong>${current.achievements[key]?'🏆':'🔒'} ${def.title}</strong><span>${current.questions}/${def.targetQuestions} · ${current.accuracy}%</span><small>${def.description}</small></div>`).join('')}</article>`;}).join('')}</section>`).join('')||'<p class="muted">No chapter progress yet.</p>';this.renderTrophyRoom(progress);
  }
};
document.addEventListener('DOMContentLoaded',()=>{if(typeof Achievements!=='undefined')Achievements.load();});
